jobs:
  build:
    docker:
      - image: circleci/node:8.3.0
      
    working_directory: ~/repo

    steps:
      - checkout:
      - run: printenv
      - run:
          name: Set enviropnment variable and run test
          command: | 
            export APPLITOOLS_API_KEY
            npm install
            npm test